//! Migrations applied to a database that already has rows.
//!
//! #63. Every test in this crate applied the seventeen migrations to an empty database —
//! `migrated_pool()` in `repositories/transcript.rs` connects to `sqlite::memory:` and migrates
//! it, and production's `manager.rs:35` is the only other call site. So **eight migrations whose
//! whole purpose is to change rows that already exist have never, in any test, changed one.**
//! A migration that runs over zero rows and a migration that does the wrong thing are
//! indistinguishable in a green suite, which is the state this file ends.
//!
//! The eight, by the rule *"contains at least one statement whose effect depends on rows that
//! existed before it ran"*:
//!
//! | version | what depends on existing rows |
//! |---|---|
//! | `20250920155811` | `INSERT INTO settings_new SELECT *` — a **positional** copy |
//! | `20251105120000` | `DROP TABLE IF EXISTS licensing` and recreate |
//! | `20251110000000` | `ADD COLUMN … NOT NULL DEFAULT 604800` — writes every row |
//! | `20260806000000` | `UPDATE … WHERE provider IN (…)` |
//! | `20260806000001` | two `UPDATE`s |
//! | `20260806000002` | two `UPDATE`s, **order-dependent** |
//! | `20260807000000` | `DROP TABLE IF EXISTS licensing` |
//! | `20260811000000` | an explicit backfill, two `INSERT … SELECT` |
//!
//! **Why `run_to` and not `.sqlite` fixtures.** `git diff --stat v1.2.0 HEAD -- migrations/` and
//! `v1.4.1 HEAD` show migrations 1–16 are byte-identical to their tags, so
//! `Migrator::run_to(version, pool)` reproduces every shipped schema from the same source of
//! truth. A committed binary would be a second source that could drift from it, and could only
//! be regenerated by the code it exists to check.
//!
//! **Not here, deliberately:** the legacy `.db` import path. It fails today with
//! `duplicate column name: folder_path` (#68), and covering it here would make this suite red for
//! a defect this change does not fix.
#![cfg(test)]

use sqlx::migrate::Migrator;
use sqlx::sqlite::SqlitePoolOptions;
use sqlx::{Row, SqlitePool};

static MIGRATOR: Migrator = sqlx::migrate!("./migrations");

// The eight versions above, named rather than repeated as literals at each call site.
const SETTINGS_REBUILD: i64 = 20250920155811;
const LICENSING_RECREATE: i64 = 20251105120000;
const GRACE_PERIOD: i64 = 20251110000000;
const COLLAPSE_LOCAL: i64 = 20260806000000;
const REPAIR_STALE: i64 = 20260806000001;
const BUILTIN_AUDIO: i64 = 20260806000002;
const DROP_LICENSING: i64 = 20260807000000;
const SEARCH_BACKFILL: i64 = 20260811000000;

/// A pool migrated up to and including `version`, and no further.
///
/// `max_connections(1)`: every connection to `sqlite::memory:` opens its own database, so a
/// multi-connection pool would migrate one and query another — the same reason
/// `repositories/transcript.rs` says so.
async fn schema_at(version: i64) -> SqlitePool {
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect("sqlite::memory:")
        .await
        .expect("in-memory sqlite");
    apply(&pool, version).await;
    pool
}

/// The schema immediately before `version` — where a fixture is seeded so that `version` has
/// something to transform.
async fn schema_before(version: i64) -> SqlitePool {
    let previous = MIGRATOR
        .iter()
        .map(|m| m.version)
        .filter(|&v| v < version)
        .max()
        .unwrap_or_else(|| panic!("{version} is the first migration; nothing precedes it"));
    schema_at(previous).await
}

/// `Acquire` is implemented for `&Pool` with the pool's own lifetime, which a `&SqlitePool`
/// parameter cannot satisfy inside an `async fn`. Acquiring a connection first sidesteps that:
/// `&mut SqliteConnection` implements `Acquire` with a lifetime this function owns. The single
/// connection is also what `sqlite::memory:` requires — see `schema_at`.
async fn apply(pool: &SqlitePool, version: i64) {
    let mut conn = pool.acquire().await.expect("a connection from the pool");
    MIGRATOR
        .run_to(version, &mut *conn)
        .await
        .unwrap_or_else(|e| panic!("applying {version} failed: {e}"));
}

async fn run_all(pool: &SqlitePool) {
    let mut conn = pool.acquire().await.expect("a connection from the pool");
    MIGRATOR
        .run(&mut *conn)
        .await
        .expect("a populated database migrates to head");
}

/// `&'static str` and a bound parameter rather than a formatted string: sqlx 0.9 refuses
/// dynamic SQL outright ("dynamic SQL strings should be audited for possible injections"), and
/// interpolating an id into a query in a test is how the habit reaches production.
async fn one_string(pool: &SqlitePool, sql: &'static str, bind: &str) -> String {
    let mut conn = pool.acquire().await.expect("a connection");
    sqlx::query(sql)
        .bind(bind.to_owned())
        .fetch_one(&mut *conn)
        .await
        .unwrap_or_else(|e| panic!("{sql} [{bind}]: {e}"))
        .get::<String, _>(0)
}

async fn count(pool: &SqlitePool, sql: &'static str) -> i64 {
    let mut conn = pool.acquire().await.expect("a connection");
    sqlx::query(sql)
        .fetch_one(&mut *conn)
        .await
        .unwrap_or_else(|e| panic!("{sql}: {e}"))
        .get::<i64, _>(0)
}

// --------------------------------------------------------------------------------------------

/// The set is pinned here so a nineteenth migration that transforms rows cannot be added without
/// this file noticing. `Clause`-style: the count is the assertion.
#[test]
fn the_migration_set_is_the_one_this_file_covers() {
    let versions: Vec<i64> = MIGRATOR.iter().map(|m| m.version).collect();
    assert_eq!(
        versions.len(),
        17,
        "the migration set changed. If the new one transforms existing rows it needs a test here; \
         if it does not, say so in the pull request and update this number."
    );
    for covered in [
        SETTINGS_REBUILD,
        LICENSING_RECREATE,
        GRACE_PERIOD,
        COLLAPSE_LOCAL,
        REPAIR_STALE,
        BUILTIN_AUDIO,
        DROP_LICENSING,
        SEARCH_BACKFILL,
    ] {
        assert!(versions.contains(&covered), "migration {covered} is gone");
    }
}

/// `INSERT INTO settings_new SELECT *, NULL` is **positional**. If a column is ever reordered in
/// either table, values slide silently between columns — an API key landing in the model field is
/// not a crash, it is a wrong value the user then has to explain.
#[tokio::test]
async fn the_settings_rebuild_keeps_every_value_in_its_own_column() {
    let pool = schema_before(SETTINGS_REBUILD).await;
    sqlx::query(
        "INSERT INTO settings (id, provider, model, whisperModel, groqApiKey, openaiApiKey, \
         anthropicApiKey, ollamaApiKey) VALUES ('s1','prov-1','model-1','whisper-1','groq-1',\
         'openai-1','anthropic-1','ollama-1')",
    )
    .execute(&pool)
    .await
    .unwrap();

    apply(&pool, SETTINGS_REBUILD).await;

    let row = sqlx::query("SELECT * FROM settings WHERE id = 's1'")
        .fetch_one(&pool)
        .await
        .expect("the row survived the rebuild");
    for (column, expected) in [
        ("provider", "prov-1"),
        ("model", "model-1"),
        ("whisperModel", "whisper-1"),
        ("groqApiKey", "groq-1"),
        ("openaiApiKey", "openai-1"),
        ("anthropicApiKey", "anthropic-1"),
        ("ollamaApiKey", "ollama-1"),
    ] {
        assert_eq!(
            row.get::<String, _>(column),
            expected,
            "{column} did not survive the positional SELECT * rebuild"
        );
    }
    assert!(
        row.get::<Option<String>, _>("openRouterApiKey").is_none(),
        "the new column must arrive NULL, not carrying another column's value"
    );
}

/// `ADD COLUMN … NOT NULL DEFAULT 604800` writes every row that already exists. On an empty
/// table it writes none, which is every test before this one.
#[tokio::test]
async fn the_grace_period_default_reaches_rows_that_predate_the_column() {
    let pool = schema_before(GRACE_PERIOD).await;
    sqlx::query(
        "INSERT INTO licensing (license_key, encrypted_key, signature_hash, activation_date, \
         expiry_date, soft_expiry_date, max_activation_time, duration, generated_on) \
         VALUES ('k','enc','sha','2026-01-01','2026-02-01','2026-02-08','2026-03-01',86400,'2026-01-01')",
    )
    .execute(&pool)
    .await
    .unwrap();

    apply(&pool, GRACE_PERIOD).await;

    assert_eq!(
        count(&pool, "SELECT grace_period FROM licensing WHERE license_key = 'k'").await,
        604_800,
        "a row that existed before the column was added did not get the default"
    );
}

/// The three provider migrations, in the order they ship. Seeded once, before the first of them,
/// so what is observed is the *sequence* — which is how a user's row actually meets them.
#[tokio::test]
async fn the_provider_migrations_move_every_stale_row_they_name() {
    let pool = schema_before(COLLAPSE_LOCAL).await;
    for (id, provider, model) in [
        ("a", "localWhisper", "whisper-small"),
        ("b", "whisper", "whisper-tiny"),
        ("c", "parakeet", "parakeet-tdt-0.6b-v3-int8"),
        ("d", "local", "moonshine-streaming-small"),
        ("e", "local", "moonshine-streaming-tiny"),
    ] {
        sqlx::query("INSERT INTO transcript_settings (id, provider, model) VALUES (?, ?, ?)")
            .bind(id)
            .bind(provider)
            .bind(model)
            .execute(&pool)
            .await
            .unwrap();
    }

    apply(&pool, COLLAPSE_LOCAL).await;
    for id in ["a", "b", "c"] {
        assert_eq!(
            one_string(&pool, "SELECT provider FROM transcript_settings WHERE id = ?", id).await,
            "local",
            "row {id} was left on a provider the application no longer has"
        );
    }

    apply(&pool, REPAIR_STALE).await;
    assert_eq!(
        one_string(&pool, "SELECT model FROM transcript_settings WHERE id = ?", "d").await,
        "moonshine-streaming-small-q8",
        "the moonshine rows must gain the quantisation suffix"
    );
    assert_eq!(
        one_string(&pool, "SELECT model FROM transcript_settings WHERE id = ?", "e").await,
        "moonshine-streaming-tiny-q8"
    );
    assert_eq!(
        one_string(&pool, "SELECT model FROM transcript_settings WHERE id = ?", "c").await,
        "nemotron-3.5-asr-streaming-0.6b-q8",
        "the int8 parakeet model no longer exists and must be repaired"
    );
}

/// `20260806000002` is two `UPDATE`s and **the order between them is the behaviour**: the first
/// moves the two named gemma models to `builtin-ai` keeping their model string, and the second
/// sweeps every *remaining* ollama row onto `gemma4:e4b`. Swap them and the first row silently
/// gets `e4b` too. Nothing before this test could tell the two orders apart.
#[tokio::test]
async fn the_builtin_audio_migration_depends_on_the_order_of_its_two_updates() {
    let pool = schema_before(BUILTIN_AUDIO).await;
    for (id, model) in [("named", "gemma4:e2b"), ("other", "llama3")] {
        sqlx::query("INSERT INTO transcript_settings (id, provider, model) VALUES (?, 'ollama', ?)")
            .bind(id)
            .bind(model)
            .execute(&pool)
            .await
            .unwrap();
    }

    apply(&pool, BUILTIN_AUDIO).await;

    assert_eq!(
        one_string(&pool, "SELECT model FROM transcript_settings WHERE id = ?", "named").await,
        "gemma4:e2b",
        "a row already naming a supported gemma model must keep it — if the second UPDATE ran \
         first, this would read gemma4:e4b and the user's smaller model would have been replaced"
    );
    assert_eq!(
        one_string(&pool, "SELECT model FROM transcript_settings WHERE id = ?", "other").await,
        "gemma4:e4b",
        "an ollama row on an unsupported model must be moved to the default"
    );
    for id in ["named", "other"] {
        assert_eq!(
            one_string(&pool, "SELECT provider FROM transcript_settings WHERE id = ?", id).await,
            "builtin-ai"
        );
    }
}

/// The licensing table is created, populated, and dropped across three migrations. What matters
/// is that dropping it leaves everything else alone — a `DROP TABLE` in a file that also touches
/// other tables is where a wrong name costs a user their meetings.
#[tokio::test]
async fn dropping_licensing_leaves_the_rest_of_the_database_intact() {
    let pool = schema_before(LICENSING_RECREATE).await;
    sqlx::query("INSERT INTO meetings (id, title, created_at, updated_at) VALUES ('m1','Kept','t','t')")
        .execute(&pool)
        .await
        .unwrap();
    sqlx::query(
        "INSERT INTO transcripts (id, meeting_id, transcript, timestamp) \
         VALUES ('t1','m1','words that must survive','t')",
    )
    .execute(&pool)
    .await
    .unwrap();

    apply(&pool, DROP_LICENSING).await;

    assert_eq!(
        count(&pool, "SELECT count(*) FROM sqlite_master WHERE type='table' AND name='licensing'").await,
        0,
        "the licensing table is gone"
    );
    assert_eq!(
        one_string(&pool, "SELECT transcript FROM transcripts WHERE id = ?", "t1").await,
        "words that must survive"
    );
    assert_eq!(count(&pool, "SELECT count(*) FROM meetings").await, 1);
}

/// The backfill is the largest piece of SQL in the set and the only one that reads two tables and
/// walks JSON. On an empty database both `INSERT … SELECT` statements insert nothing, so until
/// now the `json_tree` extraction had never run at all.
#[tokio::test]
async fn the_search_backfill_indexes_transcripts_and_summaries_that_already_exist() {
    let pool = schema_before(SEARCH_BACKFILL).await;
    sqlx::query("INSERT INTO meetings (id, title, created_at, updated_at) VALUES ('m1','M','t','t')")
        .execute(&pool)
        .await
        .unwrap();
    sqlx::query(
        "INSERT INTO transcripts (id, meeting_id, transcript, timestamp) \
         VALUES ('t1','m1','findable transcript text','2026-01-01')",
    )
    .execute(&pool)
    .await
    .unwrap();
    sqlx::query(
        "INSERT INTO summary_processes (meeting_id, status, created_at, updated_at, result) \
         VALUES ('m1','done','t','t', json('{\"blocks\":[{\"title\":\"findable heading\",\
         \"content\":\"findable summary prose\"}]}'))",
    )
    .execute(&pool)
    .await
    .unwrap();
    // A row whose result is not JSON at all: the `json_valid` guard must skip it rather than
    // failing the whole migration and taking the user's database with it.
    sqlx::query("INSERT INTO meetings (id, title, created_at, updated_at) VALUES ('m2','M2','t','t')")
        .execute(&pool)
        .await
        .unwrap();
    sqlx::query(
        "INSERT INTO summary_processes (meeting_id, status, created_at, updated_at, result) \
         VALUES ('m2','done','t','t','plain text, not json')",
    )
    .execute(&pool)
    .await
    .unwrap();

    apply(&pool, SEARCH_BACKFILL).await;

    assert_eq!(
        count(&pool, "SELECT count(*) FROM search_index WHERE kind = 'transcript'").await,
        1,
        "a transcript that existed before the index was added was not indexed"
    );
    assert_eq!(
        count(&pool, "SELECT count(*) FROM search_index WHERE kind = 'summary'").await,
        1,
        "the summary prose was not extracted from JSON, or the non-JSON row was indexed anyway"
    );
    assert!(
        one_string(&pool, "SELECT text FROM search_index WHERE kind = ?", "summary").await
            .contains("findable summary prose"),
        "json_tree did not reach the content field"
    );
}

/// Everything above runs to a partial schema. This one confirms the whole sequence still lands on
/// a database that has rows at every step — the shape a real upgrade has.
#[tokio::test]
async fn a_populated_database_migrates_all_the_way_to_head() {
    let pool = schema_at(MIGRATOR.iter().next().unwrap().version).await;
    sqlx::query("INSERT INTO meetings (id, title, created_at, updated_at) VALUES ('m1','M','t','t')")
        .execute(&pool)
        .await
        .unwrap();
    sqlx::query(
        "INSERT INTO transcripts (id, meeting_id, transcript, timestamp) \
         VALUES ('t1','m1','survives seventeen migrations','t')",
    )
    .execute(&pool)
    .await
    .unwrap();
    sqlx::query("INSERT INTO transcript_settings (id, provider, model) VALUES ('x','whisper','whisper-small')")
        .execute(&pool)
        .await
        .unwrap();

    run_all(&pool).await;

    assert_eq!(
        one_string(&pool, "SELECT transcript FROM transcripts WHERE id = ?", "t1").await,
        "survives seventeen migrations"
    );
    assert_eq!(
        one_string(&pool, "SELECT provider FROM transcript_settings WHERE id = ?", "x").await,
        "local"
    );
}

/// Editing a migration that has already been applied somewhere is a real event here: `be8e5cb`
/// *"hotfix: migration fix for pro v0.1.9 compatibility"* (2025-12-31) changed two already-shipped
/// files. Comment lines only — but `checksum_with` hashes the whole text and this repository has no
/// `sqlx.toml`, so nothing is ignored, and a user whose database recorded the old bytes would meet
/// `VersionMismatch` on next launch.
///
/// The control cannot be "edit a migration and watch this go red": `sqlx::migrate!` is a
/// **compile-time** macro that emits `include_str!` and a `const` checksum, and calls
/// `proc_macro::tracked::path()`, so editing forces a rebuild and both sides then agree. What can be
/// staged is the other half — a database carrying a checksum the binary does not.
#[tokio::test]
async fn a_database_carrying_a_different_checksum_is_refused() {
    let pool = schema_at(MIGRATOR.iter().next().unwrap().version).await;

    let mut conn = pool.acquire().await.expect("a connection");
    let rows = sqlx::query("UPDATE _sqlx_migrations SET checksum = ? WHERE version = ?")
        .bind(vec![0u8; 48])
        .bind(MIGRATOR.iter().next().unwrap().version)
        .execute(&mut *conn)
        .await
        .expect("the bookkeeping table exists and is writable")
        .rows_affected();
    assert_eq!(rows, 1, "no bookkeeping row to corrupt — the setup is wrong, not the assertion");
    drop(conn);

    let mut conn = pool.acquire().await.expect("a connection");
    let err = MIGRATOR
        .run(&mut *conn)
        .await
        .expect_err("a database whose recorded checksum differs must be refused, not migrated");
    assert!(
        matches!(err, sqlx::migrate::MigrateError::VersionMismatch(_)),
        "expected VersionMismatch, got {err:?} — if this becomes some other error the failure a \
         user sees changes, and the message they report changes with it"
    );
}

/// The gap the backfill control made visible.
///
/// `20260811000000` creates the index **and** three triggers that keep it current, and the
/// `json_tree` extraction is written out three times — at lines 53 and 64 in triggers and at 89
/// in the backfill. My first control mutated line 53 and nothing went red, because no test
/// touched the triggers: the backfill covers rows that existed, and the triggers cover every row
/// after. Both halves are the same three lines of SQL and only one was observed.
#[tokio::test]
async fn the_index_triggers_keep_up_with_rows_written_after_the_migration() {
    let pool = schema_at(SEARCH_BACKFILL).await;
    sqlx::query("INSERT INTO meetings (id, title, created_at, updated_at) VALUES ('m1','M','t','t')")
        .execute(&pool)
        .await
        .unwrap();
    sqlx::query(
        "INSERT INTO transcripts (id, meeting_id, transcript, timestamp) \
         VALUES ('t1','m1','written after the index existed','2026-01-01')",
    )
    .execute(&pool)
    .await
    .unwrap();
    sqlx::query(
        "INSERT INTO summary_processes (meeting_id, status, created_at, updated_at, result) \
         VALUES ('m1','done','t','t', json('{\"blocks\":[{\"content\":\"summary written later\"}]}'))",
    )
    .execute(&pool)
    .await
    .unwrap();

    assert_eq!(
        count(&pool, "SELECT count(*) FROM search_index WHERE kind = 'transcript'").await,
        1,
        "a transcript inserted after the migration was not indexed by the trigger"
    );
    assert!(
        one_string(&pool, "SELECT text FROM search_index WHERE kind = ?", "summary").await
            .contains("summary written later"),
        "a summary inserted after the migration was not indexed by the trigger"
    );
}
