/// Application configuration constants
///
/// Centralized definitions for default models and settings.
/// Used across database initialization, import, and retranscription.

/// Transcript provider for models that run locally through transcribe.cpp.
pub const LOCAL_TRANSCRIPT_PROVIDER: &str = "local";

/// Transcript provider for audio-capable LLMs run by the bundled llama-helper
/// sidecar — the same provider name summaries already use, because it is the same
/// process and the same loaded weights.
///
/// Audio-capable models are defined once, in `summary_engine::models`, and marked
/// by carrying a projector. There is no separate transcription catalog for them.
pub const BUILTIN_TRANSCRIPT_PROVIDER: &str = "builtin-ai";

/// Default built-in transcription model when the provider is selected.
///
/// Deliberately the same tag as `DEFAULT_SUMMARY_MODEL`: one download, one model
/// resident in memory, both jobs.
pub const DEFAULT_BUILTIN_TRANSCRIBE_MODEL: &str = "gemma4:e2b";

/// Recommended model for summarization, and the one onboarding downloads.
///
/// The smaller Gemma 4 tier: ~3.6 GiB instead of ~5.3 GiB and it runs on 8 GB
/// machines, so first launch works everywhere. E4B stays one click away in
/// Model Settings for anyone who wants the better summaries.
pub const DEFAULT_SUMMARY_MODEL: &str = "gemma4:e2b";

/// True when this transcript provider runs through the built-in sidecar rather
/// than a local GGUF through transcribe.cpp.
pub fn is_builtin_transcript_provider(provider: &str) -> bool {
    provider == BUILTIN_TRANSCRIPT_PROVIDER
}

/// Default transcribe.cpp model. Chosen on WER: 1.94% on LibriSpeech test-clean
/// against nemotron-3.5's 3.06%, at the same download size.
///
/// Batch-only, so the live path segments with VAD and decodes each segment whole:
/// no `transcript-partial` events, and text lands one segment at a time
/// (`LIVE_MAX_SEGMENT_SAMPLES`, 8s) rather than as you speak. Its "Medium" speed
/// is what keeps that sustainable — a "Slow" model falls behind real time and
/// `segmented.rs` drops the oldest audio past the 30s backlog cap.
///
/// 25 European locales. Anyone recording Chinese, Japanese, Korean, Arabic, or
/// Hindi wants `nemotron-3.5-asr-streaming-0.6b-q8` instead, which also restores
/// word-by-word live text.
pub const DEFAULT_TRANSCRIBE_MODEL: &str = "parakeet-tdt-0.6b-v3-q8";

/// Models the picker marks "Recommended". Every catalog row is listed and
/// selectable — this only decides which ones carry the label.
///
/// The live entries are streaming-native — the exception is the default, which
/// trades that for WER (see `DEFAULT_TRANSCRIBE_MODEL`). The import entries are
/// batch-only and only worth their latency on a file.
pub const RECOMMENDED_LIVE_MODELS: &[&str] = &[
    "parakeet-tdt-0.6b-v3-q8",
    "nemotron-3.5-asr-streaming-0.6b-q8",
    "nemotron-3.5-asr-streaming-0.6b-q4",
    "moonshine-streaming-small-q8",
    "moonshine-streaming-tiny-q8",
    "moonshine-streaming-medium-q8",
];

/// Batch-only models worth surfacing for import and retranscription.
///
/// Both sit at the top of the Open ASR Leaderboard (granite-speech-4.1-2b 5.33%
/// avg WER, cohere-transcribe-03-2026 5.42%), which is what a file is worth
/// waiting for. whisper-large-v3-turbo is still in the catalog, just no longer
/// the first thing offered; parakeet-tdt-0.6b-v3 is the live default, and on a
/// file these two beat it.
pub const RECOMMENDED_IMPORT_MODELS: &[&str] = &[
    "granite-speech-4.1-2b-plus-q8",
    "cohere-transcribe-03-2026-q8",
];

/// One catalog row: a single quantization of a single transcribe.cpp variant.
#[derive(Debug, Clone, Copy)]
pub struct TranscribeModel {
    /// Stable identifier stored in `transcript_settings.model`.
    pub name: &'static str,
    /// Display family, e.g. "Whisper". The picker groups by this.
    pub family: &'static str,
    pub hf_repo: &'static str,
    pub filename: &'static str,
    pub size_mb: u32,
    pub accuracy: &'static str,
    /// Measured word error rate for this exact quantization, from the model
    /// card's own table. `None` when the card publishes none.
    ///
    /// Shown as a number in the picker, so it travels with `wer_set`: 1.27% on
    /// English read speech and 5.50% on Russian are not two points on one scale,
    /// and without the set beside it the smaller number reads as the better
    /// model. `accuracy` above is this number bucketed.
    pub wer: Option<f32>,
    /// The evaluation set `wer` was measured on; empty when `wer` is `None`.
    pub wer_set: &'static str,
    pub speed: &'static str,
    /// Whether this variant can drive `Session::stream()`.
    ///
    /// Display only — it decides the "live-capable" tag in the picker before the
    /// GGUF exists on disk. The decode path is chosen from
    /// `Capabilities::supports_streaming` on the loaded model, which is read
    /// from GGUF metadata and cannot drift.
    pub streaming: bool,
    /// The model's own `general.languages` GGUF metadata, harvested from the
    /// file header at generation time. Codes rather than prose, because the UI
    /// renders names from them and a language filter needs the list itself.
    /// The blurb this replaced drifted: it claimed 39 locales for nemotron-3.5,
    /// whose GGUF says 32.
    pub languages: &'static [&'static str],
    pub description: &'static str,
}

/// transcribe.cpp model catalog — every family transcribe.cpp supports.
///
/// Batch-only families are selectable for live recording too: the live path
/// falls back to VAD segmentation plus one `Session::run()` per speech segment
/// when the loaded model cannot stream. See `audio/transcription/stream_worker.rs`.
///
/// Generated. Edit `scripts/gen_model_catalog.py` and re-run it, not this array.
pub const TRANSCRIBE_MODEL_CATALOG: &[TranscribeModel] = &[
    // BEGIN GENERATED — see scripts/gen_model_catalog.py
    TranscribeModel {
        name: "moonshine-streaming-medium-q8",
        family: "Moonshine Streaming",
        hf_repo: "moonshine-streaming-medium-gguf",
        filename: "moonshine-streaming-medium-Q8_0.gguf",
        size_mb: 282,
        accuracy: "Good",
        wer: Some(2.16),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Moonshine Streaming",
    },
    TranscribeModel {
        name: "moonshine-streaming-small-q8",
        family: "Moonshine Streaming",
        hf_repo: "moonshine-streaming-small-gguf",
        filename: "moonshine-streaming-small-Q8_0.gguf",
        size_mb: 189,
        accuracy: "Good",
        wer: Some(2.54),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Moonshine Streaming",
    },
    TranscribeModel {
        name: "moonshine-streaming-tiny-q8",
        family: "Moonshine Streaming",
        hf_repo: "moonshine-streaming-tiny-gguf",
        filename: "moonshine-streaming-tiny-Q8_0.gguf",
        size_mb: 48,
        accuracy: "Decent",
        wer: Some(4.52),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Moonshine Streaming",
    },
    TranscribeModel {
        name: "multitalker-parakeet-streaming-0.6b-v1-q4",
        family: "Multitalker Parakeet",
        hf_repo: "multitalker-parakeet-streaming-0.6b-v1-gguf",
        filename: "multitalker-parakeet-streaming-0.6b-v1-Q4_K_M.gguf",
        size_mb: 478,
        accuracy: "Good",
        wer: Some(2.18),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Multitalker Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "multitalker-parakeet-streaming-0.6b-v1-q8",
        family: "Multitalker Parakeet",
        hf_repo: "multitalker-parakeet-streaming-0.6b-v1-gguf",
        filename: "multitalker-parakeet-streaming-0.6b-v1-Q8_0.gguf",
        size_mb: 734,
        accuracy: "Good",
        wer: Some(2.18),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Multitalker Parakeet",
    },
    TranscribeModel {
        name: "nemotron-3.5-asr-streaming-0.6b-q4",
        family: "Nemotron 3.5",
        hf_repo: "nemotron-3.5-asr-streaming-0.6b-gguf",
        filename: "nemotron-3.5-asr-streaming-0.6b-Q4_K_M.gguf",
        size_mb: 473,
        accuracy: "Good",
        wer: Some(3.28),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en-US", "en-GB", "es-US", "es-ES", "fr-FR", "fr-CA", "it-IT", "pt-BR", "pt-PT", "nl-NL", "de-DE", "tr-TR", "ru-RU", "ar-AR", "hi-IN", "ja-JP", "ko-KR", "vi-VN", "uk-UA", "pl-PL", "sv-SE", "cs-CZ", "nb-NO", "da-DK", "bg-BG", "fi-FI", "hr-HR", "sk-SK", "zh-CN", "hu-HU", "ro-RO", "et-EE"],
        description: "Nemotron 3.5 — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "nemotron-3.5-asr-streaming-0.6b-q8",
        family: "Nemotron 3.5",
        hf_repo: "nemotron-3.5-asr-streaming-0.6b-gguf",
        filename: "nemotron-3.5-asr-streaming-0.6b-Q8_0.gguf",
        size_mb: 716,
        accuracy: "Good",
        wer: Some(3.06),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en-US", "en-GB", "es-US", "es-ES", "fr-FR", "fr-CA", "it-IT", "pt-BR", "pt-PT", "nl-NL", "de-DE", "tr-TR", "ru-RU", "ar-AR", "hi-IN", "ja-JP", "ko-KR", "vi-VN", "uk-UA", "pl-PL", "sv-SE", "cs-CZ", "nb-NO", "da-DK", "bg-BG", "fi-FI", "hr-HR", "sk-SK", "zh-CN", "hu-HU", "ro-RO", "et-EE"],
        description: "Nemotron 3.5",
    },
    TranscribeModel {
        name: "nemotron-speech-streaming-en-0.6b-q4",
        family: "Nemotron Speech",
        hf_repo: "nemotron-speech-streaming-en-0.6b-gguf",
        filename: "nemotron-speech-streaming-en-0.6b-Q4_K_M.gguf",
        size_mb: 453,
        accuracy: "Good",
        wer: Some(2.38),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Nemotron Speech — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "nemotron-speech-streaming-en-0.6b-q8",
        family: "Nemotron Speech",
        hf_repo: "nemotron-speech-streaming-en-0.6b-gguf",
        filename: "nemotron-speech-streaming-en-0.6b-Q8_0.gguf",
        size_mb: 696,
        accuracy: "Good",
        wer: Some(2.31),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Nemotron Speech",
    },
    TranscribeModel {
        name: "parakeet-unified-en-0.6b-q4",
        family: "Parakeet Unified",
        hf_repo: "parakeet-unified-en-0.6b-gguf",
        filename: "parakeet-unified-en-0.6b-Q4_K_M.gguf",
        size_mb: 477,
        accuracy: "High",
        wer: Some(1.62),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Parakeet Unified — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-unified-en-0.6b-q8",
        family: "Parakeet Unified",
        hf_repo: "parakeet-unified-en-0.6b-gguf",
        filename: "parakeet-unified-en-0.6b-Q8_0.gguf",
        size_mb: 731,
        accuracy: "High",
        wer: Some(1.60),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: true,
        languages: &["en"],
        description: "Parakeet Unified",
    },
    TranscribeModel {
        name: "voxtral-mini-4b-realtime-2602-q4",
        family: "Voxtral Realtime",
        hf_repo: "Voxtral-Mini-4B-Realtime-2602-gguf",
        filename: "Voxtral-Mini-4B-Realtime-2602-Q4_K_M.gguf",
        size_mb: 2898,
        accuracy: "Good",
        wer: Some(2.08),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: true,
        languages: &["en", "fr", "es", "de", "ru", "zh", "ja", "it", "pt", "nl", "ar", "hi", "ko"],
        description: "Voxtral Realtime — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "voxtral-mini-4b-realtime-2602-q8",
        family: "Voxtral Realtime",
        hf_repo: "Voxtral-Mini-4B-Realtime-2602-gguf",
        filename: "Voxtral-Mini-4B-Realtime-2602-Q8_0.gguf",
        size_mb: 4844,
        accuracy: "Good",
        wer: Some(2.07),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: true,
        languages: &["en", "fr", "es", "de", "ru", "zh", "ja", "it", "pt", "nl", "ar", "hi", "ko"],
        description: "Voxtral Realtime",
    },
    TranscribeModel {
        name: "canary-180m-flash-q8",
        family: "Canary",
        hf_repo: "canary-180m-flash-gguf",
        filename: "canary-180m-flash-Q8_0.gguf",
        size_mb: 208,
        accuracy: "High",
        wer: Some(1.93),
        wer_set: "LibriSpeech test-clean",
        speed: "Fast",
        streaming: false,
        languages: &["en", "de", "es", "fr"],
        description: "Canary",
    },
    TranscribeModel {
        name: "canary-1b-flash-q4",
        family: "Canary",
        hf_repo: "canary-1b-flash-gguf",
        filename: "canary-1b-flash-Q4_K_M.gguf",
        size_mb: 646,
        accuracy: "High",
        wer: Some(1.59),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en", "de", "es", "fr"],
        description: "Canary — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "canary-1b-flash-q8",
        family: "Canary",
        hf_repo: "canary-1b-flash-gguf",
        filename: "canary-1b-flash-Q8_0.gguf",
        size_mb: 1024,
        accuracy: "High",
        wer: Some(1.62),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "de", "es", "fr"],
        description: "Canary",
    },
    TranscribeModel {
        name: "canary-1b-q4",
        family: "Canary",
        hf_repo: "canary-1b-gguf",
        filename: "canary-1b-Q4_K_M.gguf",
        size_mb: 696,
        accuracy: "High",
        wer: Some(1.55),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en", "de", "es", "fr"],
        description: "Canary — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "canary-1b-q8",
        family: "Canary",
        hf_repo: "canary-1b-gguf",
        filename: "canary-1b-Q8_0.gguf",
        size_mb: 1126,
        accuracy: "High",
        wer: Some(1.55),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "de", "es", "fr"],
        description: "Canary",
    },
    TranscribeModel {
        name: "canary-1b-v2-q4",
        family: "Canary v2",
        hf_repo: "canary-1b-v2-gguf",
        filename: "canary-1b-v2-Q4_K_M.gguf",
        size_mb: 701,
        accuracy: "High",
        wer: Some(1.91),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["bg", "hr", "cs", "da", "nl", "en", "et", "fi", "fr", "de", "el", "hu", "it", "lv", "lt", "mt", "pl", "pt", "ro", "sk", "sl", "es", "sv", "ru", "uk"],
        description: "Canary v2 — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "canary-1b-v2-q8",
        family: "Canary v2",
        hf_repo: "canary-1b-v2-gguf",
        filename: "canary-1b-v2-Q8_0.gguf",
        size_mb: 1126,
        accuracy: "High",
        wer: Some(1.91),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["bg", "hr", "cs", "da", "nl", "en", "et", "fi", "fr", "de", "el", "hu", "it", "lv", "lt", "mt", "pl", "pt", "ro", "sk", "sl", "es", "sv", "ru", "uk"],
        description: "Canary v2",
    },
    TranscribeModel {
        name: "canary-qwen-2.5b-q4",
        family: "Canary-Qwen",
        hf_repo: "canary-qwen-2.5b-gguf",
        filename: "canary-qwen-2.5b-Q4_K_M.gguf",
        size_mb: 1659,
        accuracy: "High",
        wer: Some(1.63),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en"],
        description: "Canary-Qwen — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "canary-qwen-2.5b-q8",
        family: "Canary-Qwen",
        hf_repo: "canary-qwen-2.5b-gguf",
        filename: "canary-qwen-2.5b-Q8_0.gguf",
        size_mb: 2673,
        accuracy: "High",
        wer: Some(1.63),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en"],
        description: "Canary-Qwen",
    },
    TranscribeModel {
        name: "cohere-transcribe-03-2026-q4",
        family: "Cohere Transcribe",
        hf_repo: "cohere-transcribe-03-2026-gguf",
        filename: "cohere-transcribe-03-2026-Q4_K_M.gguf",
        size_mb: 1587,
        accuracy: "High",
        wer: Some(1.25),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "it", "pt", "nl", "pl", "el", "ar", "ja", "zh", "vi", "ko"],
        description: "Cohere Transcribe — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "cohere-transcribe-03-2026-q8",
        family: "Cohere Transcribe",
        hf_repo: "cohere-transcribe-03-2026-gguf",
        filename: "cohere-transcribe-03-2026-Q8_0.gguf",
        size_mb: 2468,
        accuracy: "High",
        wer: Some(1.27),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "it", "pt", "nl", "pl", "el", "ar", "ja", "zh", "vi", "ko"],
        description: "Cohere Transcribe",
    },
    TranscribeModel {
        name: "fun-asr-mlt-nano-2512-q4",
        family: "FunASR Nano MLT",
        hf_repo: "Fun-ASR-MLT-Nano-2512-gguf",
        filename: "Fun-ASR-MLT-Nano-2512-Q4_K_M.gguf",
        size_mb: 531,
        accuracy: "High",
        wer: Some(1.89),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["zh", "en", "yue", "ja", "ko", "vi", "id", "th", "ms", "tl", "ar", "hi", "bg", "hr", "cs", "da", "nl", "et", "fi", "el", "hu", "ga", "lv", "lt", "mt", "pl", "pt", "ro", "sk", "sl", "sv"],
        description: "FunASR Nano MLT — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "fun-asr-mlt-nano-2512-q8",
        family: "FunASR Nano MLT",
        hf_repo: "Fun-ASR-MLT-Nano-2512-gguf",
        filename: "Fun-ASR-MLT-Nano-2512-Q8_0.gguf",
        size_mb: 850,
        accuracy: "High",
        wer: Some(1.74),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["zh", "en", "yue", "ja", "ko", "vi", "id", "th", "ms", "tl", "ar", "hi", "bg", "hr", "cs", "da", "nl", "et", "fi", "el", "hu", "ga", "lv", "lt", "mt", "pl", "pt", "ro", "sk", "sl", "sv"],
        description: "FunASR Nano MLT",
    },
    TranscribeModel {
        name: "fun-asr-nano-2512-q4",
        family: "FunASR Nano",
        hf_repo: "Fun-ASR-Nano-2512-gguf",
        filename: "Fun-ASR-Nano-2512-Q4_K_M.gguf",
        size_mb: 531,
        accuracy: "High",
        wer: Some(1.92),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["zh", "en", "ja"],
        description: "FunASR Nano — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "fun-asr-nano-2512-q8",
        family: "FunASR Nano",
        hf_repo: "Fun-ASR-Nano-2512-gguf",
        filename: "Fun-ASR-Nano-2512-Q8_0.gguf",
        size_mb: 850,
        accuracy: "High",
        wer: Some(1.79),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["zh", "en", "ja"],
        description: "FunASR Nano",
    },
    TranscribeModel {
        name: "gigaam-v3-ctc-q8",
        family: "GigaAM",
        hf_repo: "gigaam-v3-ctc-gguf",
        filename: "gigaam-v3-ctc-Q8_0.gguf",
        size_mb: 259,
        accuracy: "Decent",
        wer: Some(8.40),
        wer_set: "FLEURS ru (Russian)",
        speed: "Fast",
        streaming: false,
        languages: &["ru"],
        description: "GigaAM",
    },
    TranscribeModel {
        name: "gigaam-v3-e2e-ctc-q8",
        family: "GigaAM",
        hf_repo: "gigaam-v3-e2e-ctc-gguf",
        filename: "gigaam-v3-e2e-ctc-Q8_0.gguf",
        size_mb: 260,
        accuracy: "Decent",
        wer: Some(5.50),
        wer_set: "FLEURS ru (Russian)",
        speed: "Fast",
        streaming: false,
        languages: &["ru"],
        description: "GigaAM",
    },
    TranscribeModel {
        name: "gigaam-v3-e2e-rnnt-q8",
        family: "GigaAM",
        hf_repo: "gigaam-v3-e2e-rnnt-gguf",
        filename: "gigaam-v3-e2e-rnnt-Q8_0.gguf",
        size_mb: 261,
        accuracy: "Decent",
        wer: Some(5.36),
        wer_set: "FLEURS ru (Russian)",
        speed: "Fast",
        streaming: false,
        languages: &["ru"],
        description: "GigaAM",
    },
    TranscribeModel {
        name: "gigaam-v3-rnnt-q8",
        family: "GigaAM",
        hf_repo: "gigaam-v3-rnnt-gguf",
        filename: "gigaam-v3-rnnt-Q8_0.gguf",
        size_mb: 260,
        accuracy: "Decent",
        wer: Some(8.08),
        wer_set: "FLEURS ru (Russian)",
        speed: "Fast",
        streaming: false,
        languages: &["ru"],
        description: "GigaAM",
    },
    TranscribeModel {
        name: "granite-4.0-1b-speech-q4",
        family: "Granite Speech",
        hf_repo: "granite-4.0-1b-speech-gguf",
        filename: "granite-4.0-1b-speech-Q4_K_M.gguf",
        size_mb: 1638,
        accuracy: "High",
        wer: Some(1.48),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt", "ja"],
        description: "Granite Speech — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "granite-4.0-1b-speech-q8",
        family: "Granite Speech",
        hf_repo: "granite-4.0-1b-speech-gguf",
        filename: "granite-4.0-1b-speech-Q8_0.gguf",
        size_mb: 2621,
        accuracy: "High",
        wer: Some(1.44),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt", "ja"],
        description: "Granite Speech",
    },
    TranscribeModel {
        name: "granite-speech-4.1-2b-nar-q4",
        family: "Granite Speech",
        hf_repo: "granite-speech-4.1-2b-nar-gguf",
        filename: "granite-speech-4.1-2b-nar-Q4_K_M.gguf",
        size_mb: 1485,
        accuracy: "High",
        wer: Some(1.35),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt"],
        description: "Granite Speech — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "granite-speech-4.1-2b-nar-q8",
        family: "Granite Speech",
        hf_repo: "granite-speech-4.1-2b-nar-gguf",
        filename: "granite-speech-4.1-2b-nar-Q8_0.gguf",
        size_mb: 2386,
        accuracy: "High",
        wer: Some(1.29),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt"],
        description: "Granite Speech",
    },
    TranscribeModel {
        name: "granite-speech-4.1-2b-plus-q4",
        family: "Granite Speech",
        hf_repo: "granite-speech-4.1-2b-plus-gguf",
        filename: "granite-speech-4.1-2b-plus-Q4_K_M.gguf",
        size_mb: 1526,
        accuracy: "High",
        wer: Some(1.56),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt"],
        description: "Granite Speech — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "granite-speech-4.1-2b-plus-q8",
        family: "Granite Speech",
        hf_repo: "granite-speech-4.1-2b-plus-gguf",
        filename: "granite-speech-4.1-2b-plus-Q8_0.gguf",
        size_mb: 2406,
        accuracy: "High",
        wer: Some(1.50),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt"],
        description: "Granite Speech",
    },
    TranscribeModel {
        name: "granite-speech-4.1-2b-q4",
        family: "Granite Speech",
        hf_repo: "granite-speech-4.1-2b-gguf",
        filename: "granite-speech-4.1-2b-Q4_K_M.gguf",
        size_mb: 1638,
        accuracy: "High",
        wer: Some(1.37),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt", "ja"],
        description: "Granite Speech — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "granite-speech-4.1-2b-q8",
        family: "Granite Speech",
        hf_repo: "granite-speech-4.1-2b-gguf",
        filename: "granite-speech-4.1-2b-Q8_0.gguf",
        size_mb: 2621,
        accuracy: "High",
        wer: Some(1.32),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "pt", "ja"],
        description: "Granite Speech",
    },
    TranscribeModel {
        name: "moonshine-base-q8",
        family: "Moonshine",
        hf_repo: "moonshine-base-gguf",
        filename: "moonshine-base-Q8_0.gguf",
        size_mb: 74,
        accuracy: "Good",
        wer: Some(3.26),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: false,
        languages: &["en"],
        description: "Moonshine",
    },
    TranscribeModel {
        name: "moonshine-tiny-q8",
        family: "Moonshine",
        hf_repo: "moonshine-tiny-gguf",
        filename: "moonshine-tiny-Q8_0.gguf",
        size_mb: 34,
        accuracy: "Decent",
        wer: Some(4.60),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: false,
        languages: &["en"],
        description: "Moonshine",
    },
    TranscribeModel {
        name: "moss-transcribe-diarize-q4",
        family: "MOSS Transcribe-Diarize",
        hf_repo: "MOSS-Transcribe-Diarize-gguf",
        filename: "MOSS-Transcribe-Diarize-Q4_K_M.gguf",
        size_mb: 617,
        accuracy: "Good",
        wer: Some(2.59),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en", "zh"],
        description: "MOSS Transcribe-Diarize — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "moss-transcribe-diarize-q8",
        family: "MOSS Transcribe-Diarize",
        hf_repo: "MOSS-Transcribe-Diarize-gguf",
        filename: "MOSS-Transcribe-Diarize-Q8_0.gguf",
        size_mb: 987,
        accuracy: "High",
        wer: Some(1.93),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en", "zh"],
        description: "MOSS Transcribe-Diarize",
    },
    TranscribeModel {
        name: "parakeet-ctc-0.6b-q4",
        family: "Parakeet",
        hf_repo: "parakeet-ctc-0.6b-gguf",
        filename: "parakeet-ctc-0.6b-Q4_K_M.gguf",
        size_mb: 469,
        accuracy: "High",
        wer: Some(1.90),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-ctc-0.6b-q8",
        family: "Parakeet",
        hf_repo: "parakeet-ctc-0.6b-gguf",
        filename: "parakeet-ctc-0.6b-Q8_0.gguf",
        size_mb: 722,
        accuracy: "High",
        wer: Some(1.87),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "parakeet-ctc-1.1b-q4",
        family: "Parakeet",
        hf_repo: "parakeet-ctc-1.1b-gguf",
        filename: "parakeet-ctc-1.1b-Q4_K_M.gguf",
        size_mb: 818,
        accuracy: "High",
        wer: Some(1.90),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-ctc-1.1b-q8",
        family: "Parakeet",
        hf_repo: "parakeet-ctc-1.1b-gguf",
        filename: "parakeet-ctc-1.1b-Q8_0.gguf",
        size_mb: 1290,
        accuracy: "High",
        wer: Some(1.85),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "parakeet-rnnt-0.6b-q4",
        family: "Parakeet",
        hf_repo: "parakeet-rnnt-0.6b-gguf",
        filename: "parakeet-rnnt-0.6b-Q4_K_M.gguf",
        size_mb: 476,
        accuracy: "High",
        wer: Some(1.59),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-rnnt-0.6b-q8",
        family: "Parakeet",
        hf_repo: "parakeet-rnnt-0.6b-gguf",
        filename: "parakeet-rnnt-0.6b-Q8_0.gguf",
        size_mb: 730,
        accuracy: "High",
        wer: Some(1.62),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "parakeet-rnnt-1.1b-q4",
        family: "Parakeet",
        hf_repo: "parakeet-rnnt-1.1b-gguf",
        filename: "parakeet-rnnt-1.1b-Q4_K_M.gguf",
        size_mb: 825,
        accuracy: "High",
        wer: Some(1.41),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-rnnt-1.1b-q8",
        family: "Parakeet",
        hf_repo: "parakeet-rnnt-1.1b-gguf",
        filename: "parakeet-rnnt-1.1b-Q8_0.gguf",
        size_mb: 1300,
        accuracy: "High",
        wer: Some(1.46),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "parakeet-tdt-0.6b-v2-q4",
        family: "Parakeet",
        hf_repo: "parakeet-tdt-0.6b-v2-gguf",
        filename: "parakeet-tdt-0.6b-v2-Q4_K_M.gguf",
        size_mb: 483,
        accuracy: "High",
        wer: Some(1.72),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-tdt-0.6b-v2-q8",
        family: "Parakeet",
        hf_repo: "parakeet-tdt-0.6b-v2-gguf",
        filename: "parakeet-tdt-0.6b-v2-Q8_0.gguf",
        size_mb: 730,
        accuracy: "High",
        wer: Some(1.69),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "parakeet-tdt-0.6b-v3-q4",
        family: "Parakeet TDT v3",
        hf_repo: "parakeet-tdt-0.6b-v3-gguf",
        filename: "parakeet-tdt-0.6b-v3-Q4_K_M.gguf",
        size_mb: 502,
        accuracy: "High",
        wer: Some(1.98),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["bg", "hr", "cs", "da", "nl", "en", "et", "fi", "fr", "de", "el", "hu", "it", "lv", "lt", "mt", "pl", "pt", "ro", "ru", "sk", "sl", "es", "sv", "uk"],
        description: "Parakeet TDT v3 — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-tdt-0.6b-v3-q8",
        family: "Parakeet TDT v3",
        hf_repo: "parakeet-tdt-0.6b-v3-gguf",
        filename: "parakeet-tdt-0.6b-v3-Q8_0.gguf",
        size_mb: 740,
        accuracy: "High",
        wer: Some(1.94),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["bg", "hr", "cs", "da", "nl", "en", "et", "fi", "fr", "de", "el", "hu", "it", "lv", "lt", "mt", "pl", "pt", "ro", "ru", "sk", "sl", "es", "sv", "uk"],
        description: "Parakeet TDT v3",
    },
    TranscribeModel {
        name: "parakeet-tdt-1.1b-q4",
        family: "Parakeet",
        hf_repo: "parakeet-tdt-1.1b-gguf",
        filename: "parakeet-tdt-1.1b-Q4_K_M.gguf",
        size_mb: 825,
        accuracy: "High",
        wer: Some(1.42),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-tdt-1.1b-q8",
        family: "Parakeet",
        hf_repo: "parakeet-tdt-1.1b-gguf",
        filename: "parakeet-tdt-1.1b-Q8_0.gguf",
        size_mb: 1300,
        accuracy: "High",
        wer: Some(1.38),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "parakeet-tdt_ctc-1.1b-q4",
        family: "Parakeet",
        hf_repo: "parakeet-tdt_ctc-1.1b-gguf",
        filename: "parakeet-tdt_ctc-1.1b-Q4_K_M.gguf",
        size_mb: 825,
        accuracy: "High",
        wer: Some(1.91),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Parakeet — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "parakeet-tdt_ctc-1.1b-q8",
        family: "Parakeet",
        hf_repo: "parakeet-tdt_ctc-1.1b-gguf",
        filename: "parakeet-tdt_ctc-1.1b-Q8_0.gguf",
        size_mb: 1300,
        accuracy: "High",
        wer: Some(1.87),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "parakeet-tdt_ctc-110m-q8",
        family: "Parakeet",
        hf_repo: "parakeet-tdt_ctc-110m-gguf",
        filename: "parakeet-tdt_ctc-110m-Q8_0.gguf",
        size_mb: 135,
        accuracy: "Good",
        wer: Some(2.43),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: false,
        languages: &["en"],
        description: "Parakeet",
    },
    TranscribeModel {
        name: "qwen3-asr-0.6b-q4",
        family: "Qwen3-ASR",
        hf_repo: "Qwen3-ASR-0.6B-gguf",
        filename: "Qwen3-ASR-0.6B-Q4_K_M.gguf",
        size_mb: 654,
        accuracy: "Good",
        wer: Some(2.26),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["zh", "en", "yue", "ar", "de", "fr", "es", "pt", "id", "it", "ko", "ru", "th", "vi", "ja", "tr", "hi", "ms", "nl", "sv", "da", "fi", "pl", "cs", "fil", "fa", "el", "ro", "hu", "mk"],
        description: "Qwen3-ASR — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "qwen3-asr-0.6b-q8",
        family: "Qwen3-ASR",
        hf_repo: "Qwen3-ASR-0.6B-gguf",
        filename: "Qwen3-ASR-0.6B-Q8_0.gguf",
        size_mb: 811,
        accuracy: "Good",
        wer: Some(2.11),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["zh", "en", "yue", "ar", "de", "fr", "es", "pt", "id", "it", "ko", "ru", "th", "vi", "ja", "tr", "hi", "ms", "nl", "sv", "da", "fi", "pl", "cs", "fil", "fa", "el", "ro", "hu", "mk"],
        description: "Qwen3-ASR",
    },
    TranscribeModel {
        name: "qwen3-asr-1.7b-q4",
        family: "Qwen3-ASR",
        hf_repo: "Qwen3-ASR-1.7B-gguf",
        filename: "Qwen3-ASR-1.7B-Q4_K_M.gguf",
        size_mb: 1259,
        accuracy: "High",
        wer: Some(1.81),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["zh", "en", "yue", "ar", "de", "fr", "es", "pt", "id", "it", "ko", "ru", "th", "vi", "ja", "tr", "hi", "ms", "nl", "sv", "da", "fi", "pl", "cs", "fil", "fa", "el", "ro", "hu", "mk"],
        description: "Qwen3-ASR — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "qwen3-asr-1.7b-q8",
        family: "Qwen3-ASR",
        hf_repo: "Qwen3-ASR-1.7B-gguf",
        filename: "Qwen3-ASR-1.7B-Q8_0.gguf",
        size_mb: 2084,
        accuracy: "High",
        wer: Some(1.61),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["zh", "en", "yue", "ar", "de", "fr", "es", "pt", "id", "it", "ko", "ru", "th", "vi", "ja", "tr", "hi", "ms", "nl", "sv", "da", "fi", "pl", "cs", "fil", "fa", "el", "ro", "hu", "mk"],
        description: "Qwen3-ASR",
    },
    TranscribeModel {
        name: "sensevoicesmall-q8",
        family: "SenseVoice",
        hf_repo: "SenseVoiceSmall-gguf",
        filename: "SenseVoiceSmall-Q8_0.gguf",
        size_mb: 241,
        accuracy: "Good",
        wer: Some(3.13),
        wer_set: "LibriSpeech test-clean",
        speed: "Fast",
        streaming: false,
        languages: &["zh", "yue", "en", "ja", "ko"],
        description: "SenseVoice",
    },
    TranscribeModel {
        name: "voxtral-mini-3b-2507-q4",
        family: "Voxtral",
        hf_repo: "Voxtral-Mini-3B-2507-gguf",
        filename: "Voxtral-Mini-3B-2507-Q4_K_M.gguf",
        size_mb: 3052,
        accuracy: "High",
        wer: Some(1.94),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "it", "pt", "nl", "hi"],
        description: "Voxtral — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "voxtral-mini-3b-2507-q8",
        family: "Voxtral",
        hf_repo: "Voxtral-Mini-3B-2507-gguf",
        filename: "Voxtral-Mini-3B-2507-Q8_0.gguf",
        size_mb: 5120,
        accuracy: "High",
        wer: Some(1.87),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["en", "fr", "de", "es", "it", "pt", "nl", "hi"],
        description: "Voxtral",
    },
    TranscribeModel {
        name: "whisper-base-q8",
        family: "Whisper",
        hf_repo: "whisper-base-gguf",
        filename: "whisper-base-Q8_0.gguf",
        size_mb: 81,
        accuracy: "Decent",
        wer: Some(5.12),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-base.en-q8",
        family: "Whisper",
        hf_repo: "whisper-base.en-gguf",
        filename: "whisper-base.en-Q8_0.gguf",
        size_mb: 81,
        accuracy: "Good",
        wer: Some(4.16),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: false,
        languages: &["en"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-large-q4",
        family: "Whisper",
        hf_repo: "whisper-large-gguf",
        filename: "whisper-large-Q4_K_M.gguf",
        size_mb: 950,
        accuracy: "Good",
        wer: Some(2.67),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "whisper-large-q8",
        family: "Whisper",
        hf_repo: "whisper-large-gguf",
        filename: "whisper-large-Q8_0.gguf",
        size_mb: 1587,
        accuracy: "Good",
        wer: Some(2.74),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-large-v2-q4",
        family: "Whisper",
        hf_repo: "whisper-large-v2-gguf",
        filename: "whisper-large-v2-Q4_K_M.gguf",
        size_mb: 950,
        accuracy: "Good",
        wer: Some(2.46),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "whisper-large-v2-q8",
        family: "Whisper",
        hf_repo: "whisper-large-v2-gguf",
        filename: "whisper-large-v2-Q8_0.gguf",
        size_mb: 1587,
        accuracy: "Good",
        wer: Some(2.65),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-large-v3-q4",
        family: "Whisper",
        hf_repo: "whisper-large-v3-gguf",
        filename: "whisper-large-v3-Q4_K_M.gguf",
        size_mb: 951,
        accuracy: "High",
        wer: Some(1.86),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "yue", "zh"],
        description: "Whisper — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "whisper-large-v3-q8",
        family: "Whisper",
        hf_repo: "whisper-large-v3-gguf",
        filename: "whisper-large-v3-Q8_0.gguf",
        size_mb: 1587,
        accuracy: "High",
        wer: Some(1.82),
        wer_set: "LibriSpeech test-clean",
        speed: "Slow",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "yue", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-large-v3-turbo-q4",
        family: "Whisper",
        hf_repo: "whisper-large-v3-turbo-gguf",
        filename: "whisper-large-v3-turbo-Q4_K_M.gguf",
        size_mb: 511,
        accuracy: "Good",
        wer: Some(2.04),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "yue", "zh"],
        description: "Whisper — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "whisper-large-v3-turbo-q8",
        family: "Whisper",
        hf_repo: "whisper-large-v3-turbo-gguf",
        filename: "whisper-large-v3-turbo-Q8_0.gguf",
        size_mb: 845,
        accuracy: "Good",
        wer: Some(2.01),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "yue", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-medium-q4",
        family: "Whisper",
        hf_repo: "whisper-medium-gguf",
        filename: "whisper-medium-Q4_K_M.gguf",
        size_mb: 481,
        accuracy: "Good",
        wer: Some(2.59),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "whisper-medium-q8",
        family: "Whisper",
        hf_repo: "whisper-medium-gguf",
        filename: "whisper-medium-Q8_0.gguf",
        size_mb: 793,
        accuracy: "Good",
        wer: Some(2.64),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-medium.en-q4",
        family: "Whisper",
        hf_repo: "whisper-medium.en-gguf",
        filename: "whisper-medium.en-Q4_K_M.gguf",
        size_mb: 481,
        accuracy: "Good",
        wer: Some(2.91),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Whisper — smaller download, lower memory use",
    },
    TranscribeModel {
        name: "whisper-medium.en-q8",
        family: "Whisper",
        hf_repo: "whisper-medium.en-gguf",
        filename: "whisper-medium.en-Q8_0.gguf",
        size_mb: 793,
        accuracy: "Good",
        wer: Some(2.72),
        wer_set: "LibriSpeech test-clean",
        speed: "Medium",
        streaming: false,
        languages: &["en"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-small-q8",
        family: "Whisper",
        hf_repo: "whisper-small-gguf",
        filename: "whisper-small-Q8_0.gguf",
        size_mb: 257,
        accuracy: "Good",
        wer: Some(3.33),
        wer_set: "LibriSpeech test-clean",
        speed: "Fast",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-small.en-q8",
        family: "Whisper",
        hf_repo: "whisper-small.en-gguf",
        filename: "whisper-small.en-Q8_0.gguf",
        size_mb: 257,
        accuracy: "Good",
        wer: Some(3.09),
        wer_set: "LibriSpeech test-clean",
        speed: "Fast",
        streaming: false,
        languages: &["en"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-tiny-q8",
        family: "Whisper",
        hf_repo: "whisper-tiny-gguf",
        filename: "whisper-tiny-Q8_0.gguf",
        size_mb: 44,
        accuracy: "Decent",
        wer: Some(7.53),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: false,
        languages: &["af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi", "fo", "fr", "gl", "gu", "haw", "ha", "he", "hi", "hr", "ht", "hu", "hy", "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb", "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru", "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw", "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi", "yi", "yo", "zh"],
        description: "Whisper",
    },
    TranscribeModel {
        name: "whisper-tiny.en-q8",
        family: "Whisper",
        hf_repo: "whisper-tiny.en-gguf",
        filename: "whisper-tiny.en-Q8_0.gguf",
        size_mb: 44,
        accuracy: "Decent",
        wer: Some(5.72),
        wer_set: "LibriSpeech test-clean",
        speed: "Very Fast",
        streaming: false,
        languages: &["en"],
        description: "Whisper",
    },
    // END GENERATED
];

/// Base URL for catalog downloads. Every model above lives under this org.
pub const TRANSCRIBE_MODEL_BASE_URL: &str = "https://huggingface.co/handy-computer";

/// Look up a catalog row by its stored name.
/// Catalog variants that attribute speakers, by name prefix so every
/// quantization tier is covered.
///
/// Not the family: `Granite Speech` holds three variants and only `-plus`
/// diarizes — the base does not advertise it and `-nar` documents its absence.
/// Not `Capabilities` either, which carries no diarization bit to read.
pub const DIARIZING_VARIANTS: &[&str] =
    &["granite-speech-4.1-2b-plus", "moss-transcribe-diarize"];

pub fn model_diarizes(name: &str) -> bool {
    transcribe_model(name)
        .is_some_and(|m| DIARIZING_VARIANTS.iter().any(|v| m.name.starts_with(v)))
}

pub fn transcribe_model(name: &str) -> Option<&'static TranscribeModel> {
    TRANSCRIBE_MODEL_CATALOG.iter().find(|m| m.name == name)
}

/// Whether the picker labels this model "Recommended".
pub fn is_recommended_model(name: &str) -> bool {
    RECOMMENDED_LIVE_MODELS.contains(&name) || RECOMMENDED_IMPORT_MODELS.contains(&name)
}


#[cfg(test)]
mod tests {
    #[test]
    fn exactly_the_documented_variants_diarize() {
        let diarizing: Vec<&str> = super::TRANSCRIBE_MODEL_CATALOG
            .iter()
            .map(|m| m.name)
            .filter(|n| super::model_diarizes(n))
            .collect();

        assert_eq!(
            diarizing,
            vec![
                "granite-speech-4.1-2b-plus-q4",
                "granite-speech-4.1-2b-plus-q8",
                "moss-transcribe-diarize-q4",
                "moss-transcribe-diarize-q8",
            ],
            "the catalog is generated; a regenerated row must not silently gain \
             or lose speaker attribution"
        );

        for sibling in ["granite-speech-4.1-2b-q8", "granite-speech-4.1-2b-nar-q8"] {
            assert!(
                !super::model_diarizes(sibling),
                "{sibling} shares the Granite Speech family but does not diarize"
            );
        }
    }

    use super::*;

    /// The catalog is generated, so the risk is not a typo but a shifted column:
    /// `wer` and `accuracy` come from the same measurement, and `wer_set` only
    /// exists when `wer` does. Tying them together here means any regeneration
    /// that mangles the rows fails before the UI shows a wrong number.
    #[test]
    fn generated_wer_agrees_with_its_accuracy_bucket() {
        for m in TRANSCRIBE_MODEL_CATALOG {
            assert_eq!(
                m.wer.is_some(),
                !m.wer_set.is_empty(),
                "{}: a WER without its eval set (or vice versa)",
                m.name
            );
            let Some(wer) = m.wer else { continue };
            // Wider than the real spread (1.25%–8.40%) on purpose: this catches a
            // number read out of the size or parameter column, not a slow model.
            assert!((0.1..30.0).contains(&wer), "{}: implausible WER {wer}", m.name);
            let bucket = if wer < 2.0 {
                "High"
            } else if wer < 4.5 {
                "Good"
            } else {
                "Decent"
            };
            assert_eq!(
                m.accuracy, bucket,
                "{}: {wer}% is {bucket}, not {}",
                m.name, m.accuracy
            );
        }
    }
}
